apiVersion: v1
kind: PersistentVolume
metadata:
  name: random-number-generator
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  awsElasticBlockStore:
    volumeID: "volume-id"
    fsType: ext4