fastlane_version "2.12.0"

default_platform :ios

app_name = "211West 1.0"
app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

platform :ios do
    desc "Deploy ios app on the appstore"

    lane :deploy do
      match(type: "appstore")
      cordova(platform: 'ios')
      appstore(ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'])
    end
end


lane :beta do
  get_certificates           # invokes cert
  get_provisioning_profile   # invokes sigh
  build_app
end

lane :release do
  build_app(scheme: "211West 1.0")
  # upload_to_app_store
end